
import { Note, InstrumentConfig } from './types';

export const NOTES: Note[] = [
  { key: 'C4', frequency: 261.63, label: 'C', isBlack: false },
  { key: 'C#4', frequency: 277.18, label: 'C#', isBlack: true },
  { key: 'D4', frequency: 293.66, label: 'D', isBlack: false },
  { key: 'D#4', frequency: 311.13, label: 'D#', isBlack: true },
  { key: 'E4', frequency: 329.63, label: 'E', isBlack: false },
  { key: 'F4', frequency: 349.23, label: 'F', isBlack: false },
  { key: 'F#4', frequency: 369.99, label: 'F#', isBlack: true },
  { key: 'G4', frequency: 392.00, label: 'G', isBlack: false },
  { key: 'G#4', frequency: 415.30, label: 'G#', isBlack: true },
  { key: 'A4', frequency: 440.00, label: 'A', isBlack: false },
  { key: 'A#4', frequency: 466.16, label: 'A#', isBlack: true },
  { key: 'B4', frequency: 493.88, label: 'B', isBlack: false },
  { key: 'C5', frequency: 523.25, label: 'C', isBlack: false },
  { key: 'C#5', frequency: 554.37, label: 'C#', isBlack: true },
  { key: 'D5', frequency: 587.33, label: 'D', isBlack: false },
  { key: 'D#5', frequency: 622.25, label: 'D#', isBlack: true },
  { key: 'E5', frequency: 659.25, label: 'E', isBlack: false },
  { key: 'F5', frequency: 698.46, label: 'F', isBlack: false },
  { key: 'F#5', frequency: 739.99, label: 'F#', isBlack: true },
  { key: 'G5', frequency: 783.99, label: 'G', isBlack: false },
  { key: 'G#5', frequency: 830.61, label: 'G#', isBlack: true },
  { key: 'A5', frequency: 880.00, label: 'A', isBlack: false },
  { key: 'A#5', frequency: 932.33, label: 'A#', isBlack: true },
  { key: 'B5', frequency: 987.77, label: 'B', isBlack: false },
];

export const INSTRUMENTS: InstrumentConfig[] = [
  {
    id: 'piano',
    name: 'Piano',
    icon: '🎹',
    attack: 0.01,
    decay: 0.1,
    sustain: 0.3,
    release: 0.8,
    oscillatorType: 'triangle',
  },
  {
    id: 'keyboard',
    name: 'Teclado',
    icon: '⌨️',
    attack: 0.02,
    decay: 0.1,
    sustain: 0.5,
    release: 0.2,
    oscillatorType: 'square',
  },
  {
    id: 'violin',
    name: 'Violino',
    icon: '🎻',
    attack: 0.25,
    decay: 0.2,
    sustain: 0.8,
    release: 0.5,
    oscillatorType: 'sawtooth',
  },
  {
    id: 'organ',
    name: 'Órgão',
    icon: '⛪',
    attack: 0.15,
    decay: 0.1,
    sustain: 1.0,
    release: 0.15,
    oscillatorType: 'sine',
  },
  {
    id: 'tuba',
    name: 'Tuba',
    icon: '🎺',
    attack: 0.12,
    decay: 0.3,
    sustain: 0.7,
    release: 0.4,
    oscillatorType: 'square',
  },
  {
    id: 'sax',
    name: 'Saxofone',
    icon: '🎷',
    attack: 0.08,
    decay: 0.2,
    sustain: 0.8,
    release: 0.3,
    oscillatorType: 'sawtooth',
  },
  {
    id: 'straight-sax',
    name: 'Sax Reto',
    icon: '🎷',
    attack: 0.05,
    decay: 0.15,
    sustain: 0.7,
    release: 0.25,
    oscillatorType: 'sine',
  },
  {
    id: 'trumpet',
    name: 'Trompete',
    icon: '🎺',
    attack: 0.05,
    decay: 0.1,
    sustain: 0.8,
    release: 0.2,
    oscillatorType: 'sawtooth',
  },
  {
    id: 'flute',
    name: 'Flauta',
    icon: '🎐',
    attack: 0.15,
    decay: 0.2,
    sustain: 0.6,
    release: 0.3,
    oscillatorType: 'sine',
  },
  {
    id: 'clarinet',
    name: 'Clarinete',
    icon: '🎵',
    attack: 0.1,
    decay: 0.1,
    sustain: 0.7,
    release: 0.2,
    oscillatorType: 'triangle',
  }
];
